- name: Prepare Parrot as a libvirt/KVM hypervisor
  hosts: parrot
  become: true
  gather_facts: true

  vars:
    base_packages:
      - qemu-system-x86
      - qemu-utils
      - libvirt-daemon
      - libvirt-daemon-system
      - libvirt-daemon-driver-qemu
      - libvirt-clients
      - virtinst
      - bridge-utils
      - cloud-image-utils
      - openssh-server

  tasks:
    - name: Ensure base virtualization packages are installed
      apt:
        name: "{{ base_packages }}"
        state: present
        update_cache: yes

    - name: Enable socket-activated libvirt (monolithic style on Parrot)
      systemd:
        name: libvirtd.socket
        enabled: true
        state: started

    - name: Enable helper sockets (ignore if not present)
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - virtlogd.socket
        - virtlockd.socket
      ignore_errors: true

    - name: Ensure default libvirt network exists
      command: virsh net-info default
      register: netinfo
      failed_when: false
      changed_when: false

    - name: Define default network if missing
      when: "'not found' in netinfo.stderr | default('')"
      copy:
        dest: /tmp/default-net.xml
        content: |
          <network>
            <name>default</name>
            <bridge name='virbr0' stp='on' delay='0'/>
            <forward mode='nat'/>
            <ip address='192.168.122.1' netmask='255.255.255.0'>
              <dhcp>
                <range start='192.168.122.100' end='192.168.122.254'/>
              </dhcp>
            </ip>
          </network>

    - name: Create default network from XML when needed
      when: "'not found' in netinfo.stderr | default('')"
      command: virsh net-define /tmp/default-net.xml

    - name: Autostart and start default network
      shell: |
        virsh net-autostart default
        virsh net-start default 2>/dev/null || true
      args:
        executable: /bin/bash

    - name: Verify libvirt connection
      command: virsh -c qemu:///system list --all
      changed_when: false
